version: '3.4'

networks:
  dev:
    driver: bridge

services:
  weatherforecastapi:
    image: ${DOCKER_REGISTRY-}weatherforecastapi
    depends_on:
     - "app_db"
    container_name: appdemo-service
    ports:
      - "5009:80"    
    build:
      context: .
      dockerfile: WeatherForecastAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID =sa;Password=casablanca;Server=host.docker.internal;Database=WeatherForecastsDb; Encrypt=false;Trusted_Connection=False;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=casablanca 
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev

volumes:
  app_data:  